default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: git_hired_development
test:
  <<: *default
  database: git_hired_test

production:
  <<: *default
  database: git_hired_production
  username: GitHired
  password: <%= ENV['GIT_HIRED_DATABASE_PASSWORD'] %>
