# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03d712be6e529695c45d5ce70ef5f7519e12a4cf5ac634c03d3e530585168747d071ec91602d7accff6aefeeaf29617c98a76552b84ab55c8cf3fed5ba8f05ce

test:
  secret_key_base: fe9c920d82574f61f424b9be2befafc6119032c1e966b9fa43aa4f5d3c5eef8f8978d96d287c5cd0dbc10cc8354a2967232c70b38469e5c280c1067f878455a1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
